site_name: AWS Lambda Powertools for Java
site_description: AWS Lambda Powertools for Java
site_author: Amazon Web Services
nav:
  - Homepage: index.md
  - Changelog: changelog.md
  - FAQs: FAQs.md
  - Core utilities:
      - core/logging.md
      - core/tracing.md
      - core/metrics.md
  - Utilities:
      - utilities/idempotency.md
      - utilities/parameters.md
      - utilities/sqs_large_message_handling.md
      - utilities/batch.md
      - utilities/validation.md
      - utilities/custom_resources.md
      - utilities/serialization.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  logo: media/aws-logo-light.svg
  favicon: media/aws-logo-light.svg
  custom_dir: docs/overrides

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: '.'
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list

copyright: Copyright &copy; 2021 Amazon Web Services

plugins:
  - git-revision-date
  - search
  - macros

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/aws-amplify.min.js
  - javascript/extra.js

extra:
  powertools:
    version: 1.14.0

repo_url: https://github.com/awslabs/aws-lambda-powertools-java
edit_uri: edit/master/docs
